export enum SubcommandEnum {
	LOGIN = 'login',
    LOGOUT = 'logout',
    HELP = 'help',
    SUBSCRIBE = 'subscribe',
    UNSUBSCRIBE = 'unsubscribe',
    TEST = 'test',
    SEARCH = 'search',
    NEW_ISSUE = 'issue',
    ISSUES = 'issues',
    PROFILE = 'me',
    REMIND = 'remind',
    CREATE= 'create',
    LIST ='list',
}
